// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbZX_PFjaUgQWo7UEl2fRThXrsrWpsKxc',
    appId: '1:296947749265:web:b9173c21acdd742dc3ca30',
    messagingSenderId: '296947749265',
    projectId: 'laundry-project-b285a',
    authDomain: 'laundry-project-b285a.firebaseapp.com',
    storageBucket: 'laundry-project-b285a.firebasestorage.app',
    measurementId: 'G-G1NE93TG6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsD4IoqebaOoUL30snnFDIvLbln-58dQU',
    appId: '1:296947749265:android:08f1f4a05b9b9baac3ca30',
    messagingSenderId: '296947749265',
    projectId: 'laundry-project-b285a',
    storageBucket: 'laundry-project-b285a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC23gHh60OFZbm4FGYjF_ADq7BFeFg8sNE',
    appId: '1:296947749265:ios:89a6bc79a59382c3c3ca30',
    messagingSenderId: '296947749265',
    projectId: 'laundry-project-b285a',
    storageBucket: 'laundry-project-b285a.firebasestorage.app',
    iosBundleId: 'com.myapps.myapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC23gHh60OFZbm4FGYjF_ADq7BFeFg8sNE',
    appId: '1:296947749265:ios:89a6bc79a59382c3c3ca30',
    messagingSenderId: '296947749265',
    projectId: 'laundry-project-b285a',
    storageBucket: 'laundry-project-b285a.firebasestorage.app',
    iosBundleId: 'com.myapps.myapps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbZX_PFjaUgQWo7UEl2fRThXrsrWpsKxc',
    appId: '1:296947749265:web:88069e4c6629b6abc3ca30',
    messagingSenderId: '296947749265',
    projectId: 'laundry-project-b285a',
    authDomain: 'laundry-project-b285a.firebaseapp.com',
    storageBucket: 'laundry-project-b285a.firebasestorage.app',
    measurementId: 'G-3NLBXTB06M',
  );
}
